accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('profile/<int:user_id>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('profile/<int:user_id>/edit/', views.ProfileEditView.as_view(), name='profile_edit'),

    # auth
    path('signup/', views.SignupView.as_view(), name='account_signup'),
    path('login/', views.LoginView.as_view(), name='account_login'),
    path('logout/', views.LogoutView.as_view(), name='account_logout'),

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('article/new/', views.ArticleCreateView.as_view(), name='article_new'),
    path('article/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/edit/', views.ArticleEditView.as_view(), name='article_edit'),
    path('article/<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),

    path('article/<int:pk>/<int:comment_id>/delete/', views.CommentDelete.as_view(), name='comment_delete'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('search/', views.SearchView.as_view(), name='search'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/flash_message.html
{% if messages %}
{% for message in messages %}
<ul class="messages list-unstyled">
    <li{% if message.tags %} class="alert alert-{{ message.tags }} text-center"{% endif %} role="alert">
        {{ message.message }}
    </li>
</ul>
{% endfor %}
{% endif %}

templates/snippets/footer.html
<footer class="py-2 bg-dark">
    <p class="m-0 text-center text-white">&copy; Sample Blog</p>
</footer>

templates/snippets/header_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:index' %}">ブログ</a>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:article_new' %}">新規投稿</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    アカウント設定
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="{% url 'accounts:profile_detail' user.id %}">
                            プロフィール
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            メールアドレス
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            パスワード
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">
                            退会
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">サインアップ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">ログイン</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>