blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('article/new/', views.ArticleCreateView.as_view(), name='article_new'),
    path('article/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/edit/', views.ArticleEditView.as_view(), name='article_edit'),
    path('article/<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),

    path('article/<int:pk>/<int:comment_id>/delete/', views.CommentDelete.as_view(), name='comment_delete'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('search/', views.SearchView.as_view(), name='search'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
import datetime

User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='カテゴリ',  on_delete=models.PROTECT)
    title = models.CharField('タイトル', max_length=30)
    content = models.TextField('本文', max_length=500)
    image = models.ImageField('画像', upload_to='blog/images/', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class CommentManager(models.Manager):
    def fetch_by_article_id(self, article_id):
        return self.filter(article_id=article_id).order_by('id').all()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField('コメント', max_length=255)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)

    objects = CommentManager()

    def __str__(self):
        return self.article.title

blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Category

User = get_user_model()

class ArticleForm(forms.Form):
    category_data = Category.objects.all()
    category_choice = {}
    for category in category_data:
        category_choice[category] = category

    title = forms.CharField(
        max_length=30,
        label='タイトル',
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
        })
        )
    category = forms.ChoiceField(
        label='カテゴリ',
        widget=forms.Select,
        choices=list(category_choice.items())
    )
    content = forms.CharField(
        max_length=500,
        label='内容',
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control mb-3',
            'rows': 10,
            'cols': 50,
        })
    )
    image = forms.ImageField(
        label='画像',
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'class': 'form-control mb-3',
        })
    )


class CommentForm(forms.Form):
    comment = forms.CharField(
        label='',
        max_length=255,
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control mb-3',
            'rows': 6,
            'cols': 50,
        })
    )

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .models import Article, Category, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from functools import reduce
from operator import and_

class IndexView(View):
    def get(self, request, *args, **kwargs):
        article_data = Article.objects.select_related('author__profile').all().order_by('-id')

        paginator = Paginator(article_data, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'blog/index.html', context= {
            'page_obj': page_obj,
            })


class ArticleCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = ArticleForm(request.POST or None)

        return render(request, 'blog/article_form.html', context={
            'form': form,
        })

    def post(self, request, *args, **kwargs):
        form = ArticleForm(
            request.POST or None,
            request.FILES or None,
            )

        if form.is_valid():
            article_data = Article()
            article_data.author = request.user
            article_data.title = form.cleaned_data['title']
            category = form.cleaned_data['category']
            category_data = Category.objects.get(name=category)
            article_data.category = category_data
            article_data.content = form.cleaned_data['content']
            article_data.image = form.cleaned_data['image']
            article_data.save()
            messages.success(request, '新規投稿が完了しました')
            return redirect('blog:index')

        return render(request, 'blog/article_form.html', context={
            'form': form
        })


class ArticleDetailView(View):
    def get(self, request, *args, **kwargs):
        article_data = Article.objects.select_related('author__profile').get(id=self.kwargs['pk'])
        comment_data = Comment.objects.filter(article_id=self.kwargs['pk']).order_by('-id')
        form = CommentForm(request.POST or None)

        return render(request, 'blog/article_detail.html', context= {
            'article_data': article_data,
            'comment_data': comment_data,
            'form': form,
        })

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST or None)
        article_data = Article.objects.get(id=self.kwargs['pk'])
        comment_data = Comment.objects.fetch_by_article_id(self.kwargs['pk'])

        if comment_form.is_valid():
            comment = Comment()
            comment.comment = comment_form.cleaned_data['comment']
            comment.article_id = self.kwargs['pk']
            comment.user_id = request.user
            comment.save()
            return redirect('blog:article_detail', article_data.id)

        return render(request, 'blog/article_detail.html', context={
            'form': comment_form,
            'article_data': article_data,
            'comment_data': comment_data,
        })

    # def delete_comment(self, request, *args, **kwargs):
    #     comment_data = Comment.objects.get(id=self.kwargs['comment_id'])
    #     comment_data.delete()
    #     return redirect('blog:article_detail')


class ArticleEditView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        article_data = Article.objects.get(id=self.kwargs['pk'])
        form = ArticleForm(
            request.POST or None,
            initial={
                'title':article_data.title,
                'category': article_data.category,
                'content':article_data.content,
                'image':article_data.image,
                'created_at':article_data.created_at,
            }
        )

        return render(request, 'blog/article_form.html', context={
            'form': form,
        })

    def post(self, request, *args, **kwargs):
        form = ArticleForm(
            request.POST or None,
            request.FILES or None,
            )

        if form.is_valid():
            article_data = Article.objects.get(id=self.kwargs['pk'])
            article_data.title = form.cleaned_data['title']
            category = form.cleaned_data['category']
            category_date = Category.objects.get(name=category)
            article_data.category = category_date
            article_data.content = form.cleaned_data['content']
            article_data.image = form.cleaned_data['image']
            article_data.save()
            messages.success(request, '内容変更が完了しました')
            return redirect('blog:article_detail', self.kwargs['pk'])

        return render(request, 'blog/article_form.html', context={
            'form': form
        })

class ArticleDeleteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        article_data = Article.objects.get(id=self.kwargs['pk'])
        article_data.delete()
        messages.success(request, '投稿削除が完了しました')
        return redirect('blog:index')


class CommentDelete(View):
    def post(self, request, *args, **kwargs):
        comment_data = Comment.objects.get(id=self.kwargs['comment_id'])
        comment_data.delete()
        return redirect('blog:article_detail', pk=self.kwargs['pk'])


class CategoryView(View):
    def get(self, request, *args, **kwargs):
        category_data = Category.objects.get(name=self.kwargs['category'])
        article_data = Article.objects.order_by('-id').filter(category=category_data)
        return render(request, 'blog/index.html', context={
            'article_data': article_data,
        })


class SearchView(View):
    def get(self, request, *args, **kwargs):
        article_data = Article.objects.order_by('-id')
        keyword = request.GET.get('keyword')

        if keyword:
            exclusion_list = set([' ', '　'])
            query_list = ''
            for word in keyword:
                if not word in exclusion_list:
                    query_list += word
            query = reduce(and_, [Q(title__icontains=q) | Q(content__icontains=q) for q in query_list])
            article_data = article_data.filter(query)

        return render(request, 'blog/index.html', context={
            'keyword': keyword,
            'page_obj': article_data,
        })

templates/blog/article_detail.html
{% extends "base.html" %}

{% block title %}ブログ | 詳細{% endblock %}

{% block content %}

<div class="container my-5">
    <h2 class="my-4">{{ article_data.title }}</h2>
    <p>{{ article_data.category }}</p>
    <hr>
    <p>{{ article_data.created_at }} by {{ article_data.author.profile.username}}</p>
    <hr>
    {% if article_data.image %}
    <div class="mb-5">
        <img src="{{ article_data.image.url }}" alt="{{ article_data.image|cut:'blog/images/' }}">
    </div>
    {% endif %}
    <p>{{ article_data.content|linebreaksbr }}</p>
    {% if user.is_authenticated %}
    <hr>
    <div class="d-flex mb-5">
        <a href="{% url 'blog:article_edit' article_data.id %}" class="btn btn-primary me-2">編集</a>
        <form method="POST" action="{% url 'blog:article_delete' article_data.pk %}">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
        </form>
    </div>
    {% endif %}

    {% if comment_data %}
    <h3 class="mb-3">コメント</h3>
    <hr>
    {% for comment in comment_data %}

    <p>
        {{ comment.user.profile.username }}さん
        {{ comment.created_at }}<br>
        {{ comment.comment }}
    </p>
    {% if comment.user_id == request.user.id %}
    <form method="POST" action="{% url 'blog:comment_delete' article_data.pk comment.pk %}">
        {% csrf_token %}
        <button class="btn btn-outline-danger" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
    </form>
    {% endif %}
    <hr>
    {% endfor %}
    {% endif %}

    {% if not article_data.author_id == request.user.id %}
    <h3 class="my-3">投稿フォーム</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">コメント</button>

    </form>
    {% endif %}

</div>

{% endblock %}

templates/blog/article_form.html
{% extends "base.html" %}

{% block title %}
{% if "new" in request.path %}
ブログ | 新規投稿
{% else %}
ブログ | 内容変更
{% endif %}
{% endblock %}

{% block content %}

<div class="container my-5">
    <h2 class="text-center my-4">
        {% if "new" in request.path %}
        新規投稿
        {% else %}
        内容変更
        {% endif %}
    </h2>

    <div class="w-50 mx-auto">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_table }}
            <button class="btn btn-primary d-block ms-auto px-5" type="submit">
                {% if "new" in request.path %}
                投稿
                {% else %}
                変更
                {% endif %}
            </button>
        </form>
    </div>

</div>

{% endblock %}

templates/blog/index.html
{% extends "base.html" %}

{% block title %}ブログ | 一覧{% endblock %}

{% block content %}
<div class="my-5 row">

    <div class="col-9">

        {% if keyword %}
        <h4 class="mb-4">「{{ keyword }}の検索結果」</h4>
        {% endif %}

        {% for article in page_obj %}
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title">{{ article.title }}<span class="small"> - {{ article.category }}</span></h2>
                <p class="card-text">{{ article.content|truncatechars:30 }}</p>
                <div class="btn btn-primary">詳細</div>
            </div>
            <div class="card-footer">
                {{ article.created_at|date}} by {{ article.author.profile.username }}
            </div>
            <a href="{% url 'blog:article_detail' article.pk %}" class="stretched-link"></a>
        </div>

        {% endfor %}

    </div>


    <div class="col-3">

        <div class="card my-4">
            <h5 class="card-header">カテゴリ</h5>
            <div class="card-body">
                <div class="row">
                    {% for category in category_data %}
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li>
                                <a href="{% url 'blog:category' category %}">
                                    {{ category.name }}
                                </a>
                            </li>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="card">
            <h5 class="card-header">検索</h5>
            <div class="caed-body">
                <form action="{% url 'blog:search' %}" method="GET" class="input-group">
                    <input type="text" class="form-control" name="keyword" placeholder="ブログを検索...">
                    <button class="btn btn-primary ms-2" type="submit">検索</button>
                </form>
            </div>
        </div>

    </div>
</div>

    <div class="pagination">
        <span class="step-links mx-auto mb-5">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endblock %}